spring:
  data:
    mongodb:
      uri: mongodb://192.168.12.200:24578/zendesk


zendesk:
  # zendesk 源站域名
  source:
    domain: https://pdi-jinmuinfo.zendesk.com
    username: user1@yzm.de
    password: 1qaz@WSX
  # zendesk 目标站域名
  target:
    domain: https://jinmu1442.zendesk.com
    username: 1102361302@qq.com
    password: 123456
  filePath: C:\\Users\\cc\\Desktop\\temp
