spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/abc


zendesk:
  # zendesk 源站域名
  source:
    domain: https://pdi-jinmuinfo.zendesk.com
    username: user1@yzm.de
    password: 1qaz@WSX
  # zendesk 目标站域名
  target:
    domain: https://jinmutraining.zendesk.com
    username: user1@nqmo.com
    password: 1qaz@WSX
  filePath: /Users/qingyuanyang/Desktop/Temp
