spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/abc


zendesk:
  # zendesk 源站域名
  source:
    domain: https://pdi-jinmuinfo.zendesk.com
    username: user1@yzm.de
    password: 1qaz@WSX
  # zendesk 目标站域名
  target:
    domain: https://jingmu.zendesk.com
    username: 2694445233@qq.com
    password: 123456
  filePath: /Users/qingyuanyang/Desktop/Temp
